#!/bin/sh
sed -e 's|.*--debug--.*||g' | \
sed -e 's|[ \t]*--.*||g' | \
sed -e 's|^[ \t]*||g' | \
sed -e '/^[ \t]*$/d' | \
gsi `dirname "$0"`/../../minify.scm \
--ident-chars "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789" \
"local" "function" "end" "break" "while" "=" "return" "if" "then" "else" "elseif" "type" "'table'" "io" "stdout" "write" "string" "char" "flush" "not" "byte" "stdin" "read" "true" "do" "or" "math" "floor"




