HOST = wat
# HOST_INTERPRETER ?= $${WAT_HOST_INTERPRETER:-wasmtime} 
HOST_INTERPRETER ?= $${WAT_HOST_INTERPRETER:-host/wat/run} 
TEST_TAGS ?= wat core variadics apply r4rs
#TEST_SKIP ?= 6-10-4-load.scm
TEST_FEATURES ?=

#TEST_FILTER = 6-10-4-load

include ../../makefile-common.mk

