HOST = clj
# `bb` has a faster startup time than `clj` but worse runtime performance
HOST_INTERPRETER = $${CLJ_HOST_INTERPRETER:-clojure -M}
# HOST_INTERPRETER = $${CLJ_HOST_INTERPRETER:-clj -M}
TEST_TAGS=clj core
include ../../makefile-common.mk
