HOST = clj
# `bb` has a faster startup time than `clj` but worse runtime performance
HOST_INTERPRETER = $${CLJ_HOST_INTERPRETER:-bb}
# HOST_INTERPRETER = $${CLJ_HOST_INTERPRETER:-clj -M}
include ../../makefile-common.mk
