(define interp-code
  '((ENTRY 4)
    (PUSH-VAR 2)
    (PUSH-VAR 2)
    (PUSH-VAR 5)
    (CALL 2)
    (CDR)
    (RETURN 0)
    (ENTRY 6)
    (PUSH-VAR 3)
    (CAR)
    (CAR)
    (PUSH-VAR 3)
    (EQ?)
    (IF 5)
    (PUSH-VAR 3)
    (CAR)
    (PUSH-VAR 2)
    (SET-CDR!)
    (RETURN 0)
    (PUSH-VAR 3)
    (CDR)
    (NULL?)
    (IF 8)
    (PUSH-VAR 3)
    (PUSH-VAR 3)
    (PUSH-VAR 3)
    (CONS)
    (PUSH-LIT 0)
    (CONS)
    (SET-CDR!)
    (RETURN 0)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (PUSH-VAR 5)
    (CDR)
    (PUSH-VAR 8)
    (JUMP 3)
    (ENTRY 6)
    (PUSH-VAR 2)
    (NULL?)
    (IF 3)
    (PUSH-VAR 3)
    (RETURN 0)
    (RETURN 0)
    (PUSH-VAR 2)
    (CAR)
    (PUSH-VAR 2)
    (CAR)
    (CONS)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-VAR 4)
    (CDR)
    (PUSH-VAR 6)
    (PUSH-VAR 10)
    (CALL 3)
    (CONS)
    (RETURN 0)
    (ENTRY 4)
    (PUSH-VAR 2)
    (SYMBOL?)
    (IF 4)
    (PUSH-VAR 2)
    (PUSH-VAR 2)
    (PUSH-VAR 8)
    (JUMP 2)
    (PUSH-VAR 2)
    (PAIR?)
    (IF 7)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CDR)
    (PUSH-VAR 4)
    (CAR)
    (PUSH-VAR 10)
    (JUMP 3)
    (PUSH-VAR 2)
    (RETURN 0)
    (RETURN 0)
    (ENTRY 6)
    (PUSH-VAR 3)
    (PUSH-LIT 0)
    (EQ?)
    (IF 3)
    (PUSH-VAR 2)
    (CAR)
    (RETURN 0)
    (PUSH-VAR 3)
    (PUSH-LIT 1)
    (EQ?)
    (IF 10)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CADR)
    (PUSH-VAR 11)
    (CALL 2)
    (PUSH-VAR 3)
    (CAR)
    (PUSH-VAR 3)
    (PUSH-VAR 9)
    (JUMP 3)
    (PUSH-VAR 3)
    (PUSH-LIT 2)
    (EQ?)
    (IF 10)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CADR)
    (PUSH-VAR 12)
    (CALL 2)
    (PUSH-VAR 3)
    (CAR)
    (PUSH-VAR 3)
    (PUSH-VAR 9)
    (JUMP 3)
    (PUSH-VAR 3)
    (PUSH-LIT 3)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (PUSH-VAR 12)
    (JUMP 2)
    (PUSH-VAR 3)
    (PUSH-LIT 4)
    (EQ?)
    (IF 5)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (PUSH-LIT 0)
    (PUSH-VAR 14)
    (JUMP 3)
    (PUSH-VAR 3)
    (PUSH-LIT 5)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (PUSH-VAR 14)
    (JUMP 2)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (PUSH-VAR 5)
    (PUSH-VAR 16)
    (JUMP 3)
    (ENTRY 4)
    (PUSH-VAR 2)
    (PUSH-VAR 2)
    (CONS)
    (RETURN 0)
    (ENTRY 6)
    (PUSH-VAR 2)
    (NULL?)
    (IF 3)
    (PUSH-VAR 3)
    (RETURN 0)
    (RETURN 0)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CDR)
    (PUSH-VAR 3)
    (PUSH-VAR 5)
    (CAR)
    (PUSH-VAR 14)
    (CALL 2)
    (PUSH-VAR 15)
    (JUMP 3)
    (ENTRY 4)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CAR)
    (CAR)
    (PUSH-VAR 11)
    (CALL 2)
    (IF 6)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CAR)
    (CADR)
    (PUSH-VAR 11)
    (JUMP 2)
    (PUSH-VAR 2)
    (CDR)
    (PAIR?)
    (IF 5)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CDR)
    (PUSH-VAR 14)
    (JUMP 2)
    (PUSH-LIT 0)
    (RETURN 0)
    (ENTRY 6)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (PUSH-VAR 16)
    (CALL 2)
    (PUSH-VAR 2)
    (PUSH-VAR 5)
    (PUSH-VAR 13)
    (CALL 2)
    (PUSH-VAR 17)
    (JUMP 2)
    (ENTRY 4)
    (PUSH-VAR 2)
    (NULL?)
    (IF 2)
    (PUSH-LIT 0)
    (RETURN 0)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CAR)
    (PUSH-VAR 11)
    (CALL 2)
    (PUSH-VAR 2)
    (PUSH-VAR 4)
    (CDR)
    (PUSH-VAR 17)
    (CALL 2)
    (CONS)
    (RETURN 0)
    (ENTRY 4)
    (PUSH-VAR 2)
    (CAR)
    (PUSH-LIT 6)
    (EQ?)
    (IF 182)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 7)
    (EQ?)
    (IF 2)
    (PUSH-VAR 15)
    (JUMP 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 8)
    (EQ?)
    (IF 2)
    (PUSH-VAR 16)
    (JUMP 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 9)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (PUSH-VAR 18)
    (JUMP 1)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 10)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (SYMBOL?)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 11)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (NULL?)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 12)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (PAIR?)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 13)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (CAR)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 14)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (CDR)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 15)
    (EQ?)
    (IF 4)
    (PUSH-VAR 1)
    (CAR)
    (CADR)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 16)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CAR)
    (PUSH-VAR 2)
    (CADR)
    (CONS)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 17)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CAR)
    (PUSH-VAR 2)
    (CADR)
    (SET-CDR!)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 18)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CADR)
    (PUSH-VAR 2)
    (CAR)
    (PUSH-VAR 6)
    (JUMP 2)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 19)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CAR)
    (PUSH-VAR 2)
    (CADR)
    (EQ?)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 20)
    (EQ?)
    (IF 3)
    (PUSH-VAR 1)
    (RETURN 0)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 21)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CADR)
    (PUSH-VAR 2)
    (CAR)
    (PUSH-VAR 20)
    (JUMP 2)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 22)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CADR)
    (PUSH-VAR 2)
    (CAR)
    (PUSH-VAR 21)
    (JUMP 2)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 23)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CAR)
    (PUSH-VAR 2)
    (CADR)
    (LT)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 24)
    (EQ?)
    (IF 6)
    (PUSH-VAR 1)
    (CAR)
    (PUSH-VAR 2)
    (CADR)
    (EQ)
    (RETURN 0)
    (PUSH-VAR 2)
    (CDR)
    (PUSH-LIT 25)
    (EQ?)
    (IF 2)
    (PUSH-VAR 20)
    (JUMP 0)
    (PUSH-LIT 0)
    (RETURN 0)
    (PUSH-VAR 1)
    (PUSH-VAR 3)
    (CAR)
    (CAR)
    (PUSH-VAR 4)
    (CDR)
    (PUSH-VAR 9)
    (CALL 3)
    (PUSH-VAR 3)
    (CAR)
    (CADR)
    (PUSH-VAR 11)
    (JUMP 2)))
