#!/bin/sh

sed \
  -e 's|.*//debug.*||g' \
  -e 's|.*//nodeZZZ.*||g' \
| gsi `dirname "$0"`/../../minify.scm \
--comment-char "/" --comment-char2 "/" \
--ident-chars "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789" \
"abstract" "await" "boolean" "break" "byte" "case" "catch" "char" "class" "const" "continue" "debugger" "default" "delete" "do" "double" "else" "enum" "export" "extends" "false" "final" "finally" "float" "for" "function" "goto" "if" "implements" "import" "in" "instanceof" "int" "interface" "let  " "long" "native" "new" "null" "package" "private" "protected" "public" "return" "short" "static" "super" "switch" "synchronized" "this" "throw" "throws" "transient" "true" "try" "typeof" "var" "void" "volatile" "while" "with" "yield" \
"Buffer" "String" "addEventListener" "alloc" "appendChild" "body" "charCodeAt" "createElement" "document" "fromCharCode" "keyCode" "length" "preventDefault" "readSync" "require" "selectionStart" "slice" "style" "value" "window" "writeSync" \
| npx google-closure-compiler --language_in=ECMASCRIPT_2020 --language_out=ECMASCRIPT_2020 \
| sed -e s"|'use strict';||" \
| tr -d '\n' \
| sed -e '$s,;$,,'
