#!/bin/sh

if [ "$LIB" = "" ]; then 
    LIB="-l r4rs/r4rs-v-io -l r4rs/sys"
fi

if [ "$HOST" = "" ]; then 
    HOST="js"
fi

gsi -:r4rs ./rsc.scm -t "$HOST" $LIB "$@" -o ./rsi."$HOST" ./lib/r4rs/rsi.scm
