#!/bin/sh

ROOTDIR="$(dirname "$0")"

if [ "$RSC_SCHEME_INTERPRETER" = "" ]; then

  # -:r4rs option appeared after v4.9.4
  # This line checks for availability.
  echo "" | gsi -:r4rs 2> /dev/null > /dev/null
  if [ $? -ne 0 ]; then
    RSC_SCHEME_INTERPRETER="gsi"
  else
    RSC_SCHEME_INTERPRETER="gsi -:r4rs"
  fi
fi

if [ "$COMPILER" = "" ]; then
    if [ "$RSC_COMPILER" = "" ]; then
        COMPILER="$RSC_SCHEME_INTERPRETER $ROOTDIR/rsc.scm"
    else
        COMPILER="$RSC_COMPILER"
    fi
fi

$COMPILER "$@"
